name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10.2]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Packages
        run: npm install
        
      - name: Build Page
        run: npm run build

      - name: Deploy to gh-pages
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Create docker image
        run: docker build -t victorheriri/gh-actions:latest .         
          
      - name: Push docker images
        run: |
          docker push victorheriri/gh-actions:latest
